[tool.poetry]
authors = ["abersheeran <me@abersheeran.com>"]
description = ""
license = "MIT"
name = "django-simple-api"
readme = "README.md"
version = "0.1.0"

homepage = "https://github.com/abersheeran/django-simple-api"
repository = "https://github.com/abersheeran/django-simple-api"

classifiers = [
  "Programming Language :: Python :: 3",
]

packages = [
  {include = "django_simple_api"},
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "*"
pytest = "^5.4.3"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
